theme: jekyll-theme-cayman

title: Hun's 머신러닝/딥러닝 정복기
description: '휴학하고 머신러닝, 딥러닝을 공부하고 있는 비전공자입니다. 공부하다가 몰랐던 개념, 부족한 개념들을 찾아 정리하고, 캐글 공모전 수상을 최종 목표로 하고 있습니다'

authors:
  sal:
    name: 김지훈
    display_name: JiHun
    gravatar: 
    email: kimji6784@gmail.com
    web: https://JiHun222.github.io
